excluded:
  - Mogakco/App/AppDelegate.swift
  - Mogakco/App/SceneDelegate.swift
opt_in_rules:
  - force_cast
  - force_unwrapping
disabled_rules:
  - leading_whitespace
  - trailing_whitespace
  - todo
